version: '3.3'
services:
  node_authentication:
    container_name: ${NODE_CONTAINER_NAME}
    user: ${NODE_USER}
    image: node:${NODE_VERSION}
    restart: always
    working_dir: /src
    env_file:
      - '.env'
    volumes:
      - ./:/src
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      - PORT=${NODE_PORT}
    command: sh -c "npm install && npm audit fix --force && npm run start:watch"
    depends_on:
      - mysql_authentication
      - mysql_authentication_test
  mysql_authentication:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWD}
      - MYSQL_USER=${MYSQL_USER_DEV}
      - MYSQL_PASSWORD=${MYSQL_PASSWD_DEV}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - './data/db/mysql:/var/lib/mysql'
      - ${SQL_DUMP}:/docker-entrypoint-initdb.d
  mysql_authentication_test:
    image: mysql:${MYSQL_VERSION_TEST}
    container_name: ${MYSQL_HOST_TEST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_TEST}
      - MYSQL_ROOT_USER=${MYSQL_USER_TEST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWD_TEST}
      - MYSQL_USER=${MYSQL_USER_DEV_TEST}
      - MYSQL_PASSWORD=${MYSQL_PASSWD_DEV_TEST}
    ports:
      - '${MYSQL_PORT_TEST}:${MYSQL_PORT}'
    volumes:
      - './data/db/mysql_testing:/var/lib/mysql'
